version: '3'
services:
  db:
    image: postgres
    volumes:
      - /home/georges/Downloads:/dados # Altere para o caminho do seu diretório local onde os arquivos csv estão
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"